name: build and test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    if: github.repository_owner == 'SubnauticaNitrox'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/package

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install BinaryPack Dependencies
      run: dotnet restore ./src/BinaryPack/BinaryPack.csproj

    - name: Install BinaryPack.Unit Dependencies
      run: dotnet restore ./unit/BinaryPack.Unit/BinaryPack.Unit.csproj

    - name: Install BinaryPack.Unit.Internals Dependencies
      run: dotnet restore ./unit/BinaryPack.Unit.Internals/BinaryPack.Unit.Internals.csproj

    - name: Build BinaryPack
      run: dotnet build ./src/BinaryPack/BinaryPack.csproj --configuration Release --no-restore

    - name: Build BinaryPack.Unit
      run: dotnet build ./unit/BinaryPack.Unit/BinaryPack.Unit.csproj --configuration Debug --no-restore

    - name: Build BinaryPack.Unit.Internals
      run: dotnet build ./unit/BinaryPack.Unit.Internals/BinaryPack.Unit.Internals.csproj --configuration Debug --no-restore

    - name: Test BinaryPack.Unit
      run: dotnet test ./unit/BinaryPack.Unit/BinaryPack.Unit.csproj --no-restore --no-build --verbosity normal

    - name: Test BinaryPack.Unit.Internals
      run: dotnet test ./unit/BinaryPack.Unit.Internals/BinaryPack.Unit.Internals.csproj --no-restore --no-build --verbosity normal